### ISSUE TITLE
commissioning error

### ISSUE THREAD

**Issue by javierbarellano4v** [mfucci/node-matter#28] opened 2022-09-22 20:50 UTC
Not sure why I'm now seeing this?

arallels@parallels-Parallels-Virtual-Platform:~$ matter
Matter server listening
Pase: Received pairing request from udp://192.168.1.11:53853
Pase: Paired succesfully with udp://192.168.1.11:53853
Received read request from udp://192.168.1.11:53853 on session secure/8585: */49/65532, 0/48/0, 0/48/1, 0/48/2, 0/48/3, 0/40/2, 0/40/4, */49/3
Received invoke request from udp://192.168.1.11:53853 on session secure/8585: 0/48/0
Received invoke request from udp://192.168.1.11:53853 on session secure/8585: 0/48/2
Received invoke request from udp://192.168.1.11:53853 on session secure/8585: 0/62/2
Received invoke request from udp://192.168.1.11:53853 on session secure/8585: 0/62/2
Received invoke request from udp://192.168.1.11:53853 on session secure/8585: 0/62/0
Received invoke request from udp://192.168.1.11:53853 on session secure/8585: 0/62/4
Received invoke request from udp://192.168.1.11:53853 on session secure/8585: 0/62/11
Received invoke request from udp://192.168.1.11:53853 on session secure/8585: 0/62/6
Case: Received pairing request from udp://192.168.1.11:53853
An error occured during the commissioning Error: CASE session resume not supported
    at CasePairing.<anonymous> (/usr/local/lib/node_modules/node-matter/build/session/secure/CasePairing.js:44:23)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/node-matter/build/session/secure/CasePairing.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by mfucci** [comment] 2022-09-22 21:53
The library currently doesn't support session resume, part of CASE session pairing.
To be honest, I didn't understand the use case for session resume (optional field of sigma1 message, see CaseMessages.ts) and the Android controller doesn't seem to use it so I was not able to test it.
Do you have any clue what is the use for it?

The code for it in CHIP seemed pretty straight forward though, so it should not take more than a few days to implement, if I have a way of reproduce this flow.
Are you using a Matter controller I can play with on my side?

You can try to ignore resumptionId rather than crashing and see if this works.
In case CasePairing.ts:
_ comment the line "if (peerResumptionId !== undefined) throw new Error("CASE session resume not supported")"
_ if needed, replace "const resumptionId = Crypto.getRandomData(16);" with "const resumptionId = peerResumptionId;"

**Comment by javierbarellano4v** [comment] 2022-09-23 20:58
Pardon the delayed response.

I have 3 deployments of the CHIP tool. On a Raspberry Pi 4/Ubuntu and MacOS, both yield this same warning but able to toggle onoff, etc. after commissioning.

Unfortunately, recently built the Android version of CHIP tool, loaded to an Android tablet but I'm unable to commission anything - crashes. '

I was trying other commands in the Android tool but i had a question regarding IDs, how do you retrieve the Fabric ID? Additionally, where is the Device ID? I see product IDs, vendor IDs, vendor type...

**Comment by javierbarellano4v** [comment] 2022-09-25 21:23
I forget to try your recommendation 

In CasePairing.js as opposed to CasePairing.ts?

![image](https://user-images.githubusercontent.com/97479879/192166178-020fc9cb-7092-4d49-a01e-3527c2e479e1.png)

**Comment by mfucci** [comment] 2022-09-26 19:58
CasePairing.js is the compiled version of CasePairing.ts.
Sure, you can modified directly the compiled version to do a quick test however it will be overridden without a warning if you rebuild (npm run build).

Just commenting the "if / throw Error" might not be enough since the code generates a new resumptionId for the server. Maybe it needs to respond with the client resumptionId instead, just a guess without digging into the code.

I might have some time today to implement support for resumptionId since it is also blocking to fix attribute subscription so stay tuned...

**Comment by mfucci** [comment] 2022-09-27 01:39
Answers to your other questions:

- fabric ID / node Id: this is defined by the controller. Created a PR to add a log when the commissioning is completed: https://github.com/mfucci/node-matter/pull/31
- device Id: you mean instance Id or node Id? Instance Id: I just pick a random number at boot, as far as I understand, this Id is not very important. Node Id: see answer above

**Comment by mfucci** [comment] 2022-09-28 01:08
This PR should implement session resumes: https://github.com/mfucci/node-matter/pull/32
Let me know if it works after this change.

**Comment by javierbarellano4v** [comment] 2022-09-28 15:23
I uninstalled node-matter (via npm). I'm a bit new to node.js, so just in case.

After launch of node-matter, attempted to pair. Attached output from chip-tool invocation.

Hope this helps.. and hopefully i have the latest updates!

![image](https://user-images.githubusercontent.com/97479879/192817564-cde6621b-d2ae-4440-8b2f-174b54d3512b.png)



[Trace chip-tool command line pairing -28 .pdf](https://github.com/mfucci/node-matter/files/9666520/Trace.chip-tool.command.line.pairing.-28.pdf)

**Comment by javierbarellano4v** [comment] 2022-09-28 15:35
Add to last comment .. chip-tool trace/log 

[out:debug:chip-tool pairing.pdf](https://github.com/mfucci/node-matter/files/9666658/out.debug.chip-tool.pairing.pdf)

**Comment by javierbarellano4v** [comment] 2022-09-28 15:37
I meant to say, i uninstalled node-matter first (npm uninstall node-matter) and then reinstalled (npm i -g node-matter).

**Comment by mfucci** [comment] 2022-09-28 22:43
`npm i node-matter` install the latest released version of node-matter

To test my fix (should be easy):

1. Clone the repo: `git clone https://github.com/mfucci/node-matter.git`
2. Switch to the fix branch: `cd node-matter` `git checkout add-session-resume`
3. Compile: `npm run build`
4. Run node-matter: `node build/Main.js`

If you want to modify the code with an IDE, I recommend Visual Studio

Let me know if this fixes the issue!
I added you as a reviewer of the PR: https://github.com/mfucci/node-matter/pull/32

**Comment by javierbarellano4v** [comment] 2022-09-29 15:01
![image](https://user-images.githubusercontent.com/97479879/193067318-5e628ea6-a7f3-43c9-bf64-66b59016f1f4.png)

Missing something? Still a node.js neophyte....

**Comment by mfucci** [comment] 2022-09-29 17:06
My bad, I forgot one step where the project dependencies are installed, to do after switch branch but before compiling

Step 2b: `npm i` . This will install all the required libraries just for this project. They are all listed in the file package.json, the typescript compiler, tsc, is provided by the dev dependency ts-node.

**Comment by javierbarellano4v** [comment] 2022-09-29 18:28
No worries at all..., appreciate your patience.

Bingo, works!

<img width="695" alt="Screen Shot 2022-09-29 at 1 17 50 PM" src="https://user-images.githubusercontent.com/97479879/193113442-9c354fa1-519b-4928-bcf6-84521199c07c.png">

**Comment by mfucci** [comment] 2022-09-30 03:13
Great, fantastic!

**Comment by javierbarellano4v** [comment] 2022-09-30 14:03
Think everything is merged now.  
Can you 'upload' new version to npm (so can install new, merged version via npm)
Thanks!

**Comment by mfucci** [comment] 2022-09-30 17:48
This is now merged in main, I will publish a new version shortly

**Closed by mfucci** 2022-09-30 17:48 UTC
