### ISSUE TITLE
Great start but I am getting an error pairing with CHIPTool

### ISSUE THREAD

**Issue by jdesai61** [mfucci/node-matter#2] opened 2022-06-21 16:38 UTC
Excellent project!

I just tried to pair with CHIPTool and here is what I get:
```

# matter
Matter server listening
Pase: Received pairing request from udp://192.168.1.63:5541 on session unsecure
/usr/lib/node_modules/node-matter/build/session/secure/SecureChannelHandler.js:17
                throw new Error(`Unexpected initial message on secure channel protocol: ${messageType.toString(16)}`);
                ^

Error: Unexpected initial message on secure channel protocol: 22
    at SecureChannelHandler.onNewExchange (/usr/lib/node_modules/node-matter/build/session/secure/SecureChannelHandler.js:17:23)
    at MatterServer.onMessage (/usr/lib/node_modules/node-matter/build/server/MatterServer.js:46:29)
    at /usr/lib/node_modules/node-matter/build/server/MatterServer.js:25:78
    at Socket.<anonymous> (/usr/lib/node_modules/node-matter/build/channel/UdpChannel.js:15:67)
    at Socket.emit (node:events:537:28)
    at UDP.onMessage [as onmessage] (node:dgram:922:8)

```

**Comment by jdesai61** [comment] 2022-06-21 17:11
I just noticed that this repository has a version of CHIPTool (I was using one I built myself). When using the CHIPTool from this repo, I the node matter code prints success. But the app on my phone just says "Pairing failed":

```
Matter server listening
Pase: Received pairing request from udp://192.168.1.63:5541 on session unsecure
Pase: Paired succesfully with udp://192.168.1.63:5541 on session unsecure
Received read request from udp://192.168.1.63:5541 on session secure/65285: */49/65532, 0/48/0, 0/48/1, 0/48/2, 0/48/3, 0/40/2, 0/40/4, */49/3
Received invoke request from udp://192.168.1.63:5541 on session secure/65285: 0/48/0
Received invoke request from udp://192.168.1.63:5541 on session secure/65285: 0/48/2
Received invoke request from udp://192.168.1.63:5541 on session secure/65285: 0/62/2
Received invoke request from udp://192.168.1.63:5541 on session secure/65285: 0/62/2
Received invoke request from udp://192.168.1.63:5541 on session secure/65285: 0/62/0
Received invoke request from udp://192.168.1.63:5541 on session secure/65285: 0/62/4
Received invoke request from udp://192.168.1.63:5541 on session secure/65285: 0/62/11
Received invoke request from udp://192.168.1.63:5541 on session secure/65285: 0/62/6

````

**Comment by mfucci** [comment] 2022-06-21 18:41
After command 0/62/6 (addNewOperationalCertificates), the Matter clients waits for detecting the device over MDNS.
This is what seems to be broken here.

So two reasons why this might not work:
1 _ most likely: my last change modifying the MDNS server broke it: I thought I tested the full flow before submitting but maybe I forgot. You can try reverting to 530535fd5443216178c9f38993ab7a3d4152502d and see if this works
2 _ other reason: my MDNS implementation is not working for your local network configuration somehow. Using Wireshark, capture the network packets during the commissioning. You look for the node-matter broadcasting that it supports "_matter._tcp.local" over MDNS after the last exchange of the log you sent.

I am currently travelling and between two planes, so I won't be able to debug for 1 or 2 days...

**Comment by jdesai61** [comment] 2022-06-21 19:04
Thanks for a quick response. The first options you suggested didn't work - get the same results after reverting to previous commit. Will try to see if I can capture network packets.

**Comment by jdesai61** [comment] 2022-06-22 14:31
Upon further examination, my server has multiple IP network interfaces and mDNS server seems to pick the first available one (which was the wrong one). I tried to work around this by hardcoding the values but it didn't work. I also had avahi-daemon running that I had to kill. Still no joy. I couldn't find where mDnsServer start method is called. I forced a start() in the constructor - but that didn't help either.

**Comment by mfucci** [comment] 2022-06-22 14:51
Thanks for the update.

Yeah, I figured out that there is a big and that start() was never called on the MDNS server. But it works anyway for me, since the Matter device announcement is sent manually by the commissioning cluster.

Multiple interfaces: i thought that might create problems to pick the 1st one, might still create the issue.

It should be compatible with Avahi-daemon: it was running for me as well. For UDP / broadcast, multiple services can use the same port...

Trying to recover from the jetlag today, so I will check this tomorrow. If I can confirm that the current does indeed work for my configuration, that will give some clues.

**Comment by mfucci** [comment] 2022-06-23 04:12
Fantastic!

To summarize:

- the core problem is that the MDNS server is not broadcasting to all interfaces
- related issue: the service IP announced over MDNS should match the device IP over the broadcast interface
- another issue found: the MDNS is never started (so it won't reply to any MDNS query, but this doesn't prevent commissioning)

I will send separate changes to address those bugs.

**Comment by mfucci** [comment] 2022-06-24 03:33
Hmm... this will require some refactoring and clean up before MDNS can be handled correctly:
* MDNS server should be aware of the interface to give the correct service IP
* MDNS server should not be a singleton, but instantiated by channel
* fabric announcement should be channel specific since WiFi / BLE / thread have there own way for advertising the Matter device

This will take a couple of days to refactor

**Comment by mfucci** [comment] 2022-07-11 15:21
This is fixed with https://github.com/mfucci/node-matter/pull/7

**Closed by mfucci** 2022-07-11 15:21 UTC
